name: modelrecords
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - setuptools
  - wheel
  - pyyaml
  - semantic_version
  - jinja2
  - omegaconf
  - requests
  - pypdf
  - openai
  - invoke
  - livereload
  - matplotlib
  - pip:
    - pytailwindcss
    - pelican[markdown]
    - pelican-redirect
    - python-dotenv
    - llama-index-core
    - llama-index-llms-openai
    - llama-index-llms-replicate
    - llama-index-embeddings-huggingface
